#!/bin/sh

echo "Running pre-push hook"
echo "Running tests"
flutter test
if [ $? -ne 0 ]; then
  echo "Unit tests failed. Aborting push."
  exit 1
fi

echo "All checks passed. Proceeding with push."
exit 0